"""Shared pipeline limits."""
import re

MAX_HISTORY_MESSAGES = 6
MAX_SUMMARY_CHUNKS = 60
MAX_COMPARISON_CHUNKS = 24
RETRIEVAL_CHUNKS = 10
RETRIEVAL_CANDIDATES = 30
MAX_TOTAL_PAGES = 500
TOKEN_PATTERN = re.compile(r"\b\w{2,}\b", re.UNICODE)
